server.port: 8086
# atUCM : true
spring:
  ucm-datasource:
    url: jdbc:oracle:thin:@147.96.85.52:1521/ABDs
    username: ABD0302
    password: lola99
    driver-class-name: oracle.jdbc.OracleDriver
  datasource:
    url: jdbc:oracle:thin:@tania05.fdi.ucm.es:1521/ABDs
    username: ABD0302
    password: lola99
    driver-class-name: oracle.jdbc.OracleDriver
    
    platform: oracle
    initialization-mode: always
    continue-on-error: true
