DROP TABLE users;
CREATE TABLE users (id INT PRIMARY KEY, username VARCHAR(255), password VARCHAR(255));

DROP SEQUENCE SEQ_USERS_ID;
CREATE SEQUENCE seq_users_id
    START WITH 1
    INCREMENT BY 1;